version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-newsletter-command: &newsletter-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}

x-env-leonis: &env-leonis
  <<: *env
  GRAPHQL_URI: ${GRAPHQL_URI-https://leonis.graphql.mindful-web.parameter1.com}

x-env-tauron: &env-tauron
  <<: *env
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.tauron.mindful-web.parameter1.com}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  all:
    <<: *newsletter-cmd
    working_dir: /root/tenants/all
    environment:
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 22095
      LIVERELOAD_PORT: 32095
      TENANT_KEY: pmmi_all
    ports:
      - "22095:80"
      - "32095:32095"

  mundo:
    <<: *newsletter-cmd
    working_dir: /root/tenants/mundo
    environment:
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 22096
      LIVERELOAD_PORT: 32096
      TENANT_KEY: pmmi_mundo
    ports:
      - "22096:80"
      - "32096:32096"

volumes:
  yarn-cache: {}
